name: Deployment

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: testdb
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: rootpassword
        ports:
          - 3306


    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Install dependencies
      run: |
        composer install -o
        export PATH="$HOME/.composer/vendor/bin:$PATH"
        npm install -g gulp-cli eslint @babel/eslint-parser
        npm install

    - name: Test Syntax
      run: ./tests/test_for_syntax_errors.sh

    - name: Test Installation
      run: ./tests/test_installation.sh

    - name: Test phpcs
      run: ./tests/test_phpcs.sh

    - name: Test eslint
      run: ./tests/test_eslint.sh

    - name: Test minification
      run : |
        find dt-assets/ -iname "*.min.js" -or -iname "*.map" -or -iname "*.min.css" -delete && rm -rf build/
        gulp
        git diff --exit-code -- . ':(exclude)package-lock.json'
