name: Tests

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: testdb
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: rootpassword
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      fail-fast: true
      matrix:
        php: ["7.2", "8.0"]

    name: PHP ${{ matrix.php }}
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Install PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php }}

    - name: Report PHP version
      run: php -v

    - name: Cache Composer dependencies
      id: cache-composer-dependencies
      uses: actions/cache@v2
      env:
        cache-name: cache-composer-dependencies
      with:
        # caching node_modules
        path: vendor
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/composer.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install Composer dependencies
      if: steps.cache-composer-dependencies.outputs.cache-hit != true
      run: |
        composer install -o
        export PATH="$HOME/.composer/vendor/bin:$PATH"

    - name: Cache global node modules
      id: cache-global-nodemodules
      uses: actions/cache@v2
      env:
        cache-name: cache-global-node-modules
      with:
        # caching node_modules
        path: /usr/lib/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: |
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install global npm dependencies
      if: steps.cache-global-nodemodules.outputs.cache-hit != true
      run: |
        npm install -g gulp-cli eslint @babel/eslint-parser

    - name: Cache node modules
      id: cache-nodemodules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # caching node_modules
        path: node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install npm Dependencies
      if: steps.cache-nodemodules.outputs.cache-hit != true
      run: |
        npm install

    - name: Test Syntax
      run: ./tests/test_for_syntax_errors.sh

    - name: Test Installation
      run: ./tests/test_installation.sh

    - name: Get changed PHP files
      id: changed-php-files
      uses: tj-actions/changed-files@v35
      with:
        files: |
          **/*.php

    - name: List all changed PHP files
      run: |
        for file in ${{ steps.changed-php-files.outputs.all_changed_files }}; do
          echo "$file was changed"
        done

    - name: Run PHPCS on changed PHP files
      run: |
        ./tests/test_phpcs.sh ${{ steps.changed-php-files.outputs.all_changed_files }}

    - name: Test eslint
      run: ./tests/test_eslint.sh

    - name: Test minification
      run : |
        find dt-assets/ -iname "*.min.js" -or -iname "*.map" -or -iname "*.min.css" -delete && rm -rf build/
        gulp
        git diff --exit-code -- . ':(exclude)package-lock.json'

    - name: PHPunitSetup
      run: ./tests/install-wp-tests.sh wordpress_test root rootpassword 127.0.0.0 latest
      shell: bash

    - name: PHPunit
      run: |
        composer require "phpunit/phpunit=8.*"
        composer require "yoast/phpunit-polyfills"
        vendor/phpunit/phpunit/phpunit --version
        WP_MULTISITE=1 vendor/phpunit/phpunit/phpunit

